### ISSUE TITLE
Only downloads the first page when using Beta skin

### ISSUE THREAD

**Issue by nar001** [Xerbo/furaffinity-dl#15]
So it works and it downloads, but it seems to only download the first page of an artist I tried it on, and I'm not sure why. Any pointers?

**Comment by nar001** [comment]
I am yes, is it a problem? 
And without the cookie it works for some reason!

**Comment by Shnatsel** [comment]
FA beta skin must have changed, so that the script can no longer find the "Next" button on the beta skin. When you do not supply a cookie, the default skin is used, which works correctly.

You can work around this issue by temporarily switching to the classic skin.

**Comment by nar001** [comment]
Fair enough, thanks!

**Comment by Shnatsel** [comment]
This is something to be fixed in the script, so reopening the issue.

**Comment by nar001** [comment]
Woops, sorry for closing then. Thanks for the help though!

**Comment by Xerbo** [comment]
This bug appears to be fixed now, closing.
