### ISSUE TITLE
Kinda stops at a point when there is no file on the page then the whole download collapses

### ISSUE THREAD

**Issue by dundundunnn** [Xerbo/furaffinity-dl#17]
I tried to download 5razor gallery but stops at the middle of the first page, only workaround for me is to download the next page, gallery/5razor/2. Also I use classic skin with cookies on

**Comment by Shnatsel** [comment]
Thank you for the report. Sadly I will not be able to address this in the next few days due to travel, but I will take a look ASAP.

**Comment by Shnatsel** [comment]
In the meanwhile, if you could do a quick test with cookies off and report the results, that would help me diagnose the issue going forward.

**Comment by dundundunnn** [comment]
figures, it skipped the empty page since it was nsfw and downloads the rest
