### ISSUE TITLE
Doesn't download descriptions of images

### ISSUE THREAD

**Issue by ShapeShifter499** [Xerbo/furaffinity-dl#22]
Sometimes half of the information in the image is the description like stories. The description should be downloaded.

**Comment by Xerbo** [comment]
Downloading descriptions was added a while ago (see image), is there a specific submission that this doesn't work on?

![Screenshot_20190829_201348](https://user-images.githubusercontent.com/23143405/63969366-9e878780-ca99-11e9-9436-9e5324885ba9.png)

**Comment by ShapeShifter499** [comment]
so wait it was supposed to be added to the image metadata?

**Comment by ShapeShifter499** [comment]
I see the issue. I totally missed the fact I needed to install eyed3 and exiftool.

Since I run Arch Linux the packages I needed were.
```
pacman -S python-eyed3 perl-image-exiftool
```
I'm sorry for the confusion, seems to work now.

**Comment by ShapeShifter499** [comment]
Actually it's missing a lot of my gallery when I try to get description

https://furaffinity.net/gallery/shapeshifter499

**Comment by ShapeShifter499** [comment]
./furaffinity-dl -c ../../cookies.txt -o ../../ShapeShifter499 gallery/ShapeShifter499

**Comment by ShapeShifter499** [comment]
Ok it does work but some metadata GUI viewers don't show it.

exiftool <image> works
