### ISSUE TITLE
Script not skipping previously downloaded files

### ISSUE THREAD

**Issue by reederda** [Xerbo/furaffinity-dl#24]
An earlier version of this script would note "file exists, skipping" when iterating through a user's updated gallery. This function seems to have stopped working.

**Comment by Xerbo** [comment]
Hopefully fixed, let me know if you have any problems with it.

I also left the metadata part in, so it will keep the description of the posts up to date.

**Comment by reederda** [comment]
Tested it out, issue resolved. Thanks!
