### ISSUE TITLE
Text files not downloading properly

### ISSUE THREAD

**Issue by reederda** [Xerbo/furaffinity-dl#26]
The script appears to have an issue with download text files, such as .pdf, .txt, and .docx. While images download with their exact filename (ie <file_id>.filename.png), text files appear to download as the page id and no extension.

**Comment by Xerbo** [comment]
Text uses the format
`https://d.facdn.net/art/USER/stories/ID/ID.FILE.EXT`

Whereas images and music use
`https://d.facdn.net/art/USER/ID/ID.FILE.EXT`

This caused cut to grab the `ID` bit instead of the `ID.FILE.EXT` bit.

**Comment by Xerbo** [comment]
I'm going to close this because it seems to be fixed.
