### ISSUE TITLE
Accounts using "beta" layout only download first page

### ISSUE THREAD

**Issue by FlynnChurch** [Xerbo/furaffinity-dl#28]
If the -c option is used with a valid cookie but the associated account uses the "beta" layout (as opposed to the "classic" one), attempting to download content will stop after the first page.

This is because next_page_url is generated by grepping for the class "button-link right"; in the "beta" layout, the Next Buttons are class "button mobile-button right" instead.  Because the grep fails to find a valid URL, the download stops after the first page.

Going into account settings and switching back to the "classic" layout fixes the problem, but it's rather inconvenient.

**Comment by Kattus** [comment]
The new theme is no longer beta as of today, and is set as the default one. (You can still choose the Classic one in settings)
https://www.furaffinity.net/journal/9364332

**Comment by Xerbo** [comment]
I've putting off doing this since I hate regex, but I'll get on this one now.

**Comment by Xerbo** [comment]
Well that was easier than I was expecting, anyways, that should fix it.

**Comment by Kattus** [comment]
It still doesn't get more than the first page sadly, seems the new button is
```html
                            <div class="inline" style="width:32%">
                                                                    <form action="/gallery/pocketpaws/2/" method="get">
                                        <button class="button standard" type="submit">Next</button>
                                    </form>
                                                            </div>
```
