### ISSUE TITLE
how do i install furaffinity-dl?

### ISSUE THREAD

**Issue by rodrinii** [Xerbo/furaffinity-dl#31]

**Comment by TMillesich** [comment]
You do not "install" it. It is just one Linux shell script file.

Look at the description in the README.md how to use it.

**Comment by rodrinii** [comment]
ok, but when i put the command chmod +x faraffinity-dl it appears chmod: cannot access 'faraffinity-dl': No such file or directory.

**Comment by post-rex** [comment]
Did you even download it?
Go to your directoy of choise where you would like to save it.
Then you can download the script by running the following command:
`wget https://raw.githubusercontent.com/Xerbo/furaffinity-dl/master/furaffinity-dl`
Now you can use `chmod +x furaffinity-dl`
Now finaly `./furaffinity-dl` should work.
This only works if you are in the directory of your choise.
You can use if from outside by using `$PATH_OF_YOUR_DIR/furaffinity-dl`.
Addintinaly you could add furaffinity-dl to your path to use it globaly by just typing `furaffinity-dl`.

Here is a quick thingy you can type into your terminal and it should work fine:
```
mkdir $HOME/.fadl
wget $HOME/.fadl https://raw.githubusercontent.com/Xerbo/furaffinity-dl/master/furaffinity-dl
chmod +x $HOME/.fadl/furaffinity-dl
echo "export PATH=$HOME/.fadl:$PATH" >> $HOME/.bashrc
```
Now you should be able to just type `furaffinity-dl` into your terminal and it will work:
If it doesn't work try reopening your terminal or just typing `bash`.
If for some reason that doesn't work please comment.

UwU

**Comment by post-rex** [comment]
Oh also i just noticed you made a type
You typed faraffinity instead of furaffinity
