### ISSUE TITLE
Only pulling the first page of (48) images

### ISSUE THREAD

**Issue by ButtNumz** [Xerbo/furaffinity-dl#32]
Looked through the closed issues and saw that this would happen with the Beta Skin, but I don't currently use it and have cleared site Data already to try and solve it.

**Comment by ButtNumz** [comment]
To get around this, you can specify page numbers in the url part of the command.
 i.e. gallery/[USER]/2 etc.

Also, I've found a few quirks with the renamer.

- It converts Apostrophes and possibly other symbols into their HTML code counterparts
- When there are slashes "/" windows can't have files named with those so they don't get used

**Comment by Xerbo** [comment]
Well I can fix the titling issue. And for the downloading since FurAffinity now uses the "beta" theme as default, furaffinity-dl works with that instead of the "classic" theme.

**Comment by Xerbo** [comment]
I've just added a flag for the classic theme, let me know if it works.

**Comment by ButtNumz** [comment]
I'm having some issues, running it like normal without the new tag downloads the files without names leaving just their extensions to constantly overwrite eachother and using the new tag throws me an error

```
--2020-01-19 18:23:07--  ftp://https/
           => ‘.listing’
Resolving https (https)... failed: Name or service not known.
wget: unable to resolve host address ‘https’
```

**Comment by ButtNumz** [comment]
Using the new tag worked for me when I used the -r tag to not rename files. Without using this tag anything that gets downloaded doesn't have a name and gets overwritten by the next file of the same type.

.png gets downloaded
another .png gets downloaded and overwrites the first
.etc

**Comment by Xerbo** [comment]
Sorry for the wait, I completely forgot about this issue. Also GitHub's auto "fix in commit message means close issue" thing sucks, feel free to reopen if this doesn't solve the problem.
