### ISSUE TITLE
Fetch Error for Flash Files

### ISSUE THREAD

**Issue by ButtNumz** [Xerbo/furaffinity-dl#33]
Whenever a flash file is encountered, an error is thrown and a `.https` file is downloaded without data. I think it's because the directory for where these files are linked from were changed. Every time this happens, a batch stops and has to be restarted.

```
ftp://https/
           => ‘.listing’
Resolving https (https)... failed: Name or service not known.
wget: unable to resolve host address ‘https’
```

**Comment by Xerbo** [comment]
I would try and fix downloading of flash, but I cant actually find any flash content on FA.
If you wanted just wanted to ignore the error and continue you could do something `wget "$image_url" -O "$file" || true` at line 175.

**Comment by Kattus** [comment]
furaffinity changed the download button URL again, I've sent a PR to fix this.

**Comment by Xerbo** [comment]
Thanks (again) for the patch. Honestly this thing needs a rewrite in something that isn't shell. Also some unit tests would probably be useful, along with a development branch.

**Comment by Kattus** [comment]
It certainly isn't pretty, and I'm toying with a re-write time to time, but as long as it works it's good enough! ;p

**Comment by Xerbo** [comment]
Well, look what happened, hopefully this python version is more robust than the current one. Oh and closing this issue since its been patched.
