### ISSUE TITLE
Can't fetch anything.

### ISSUE THREAD

**Issue by serveral1** [Xerbo/furaffinity-dl#34]
Been using the bash script for quite some time already and yesterday when I tried to download a gallery it began throwing this "https:: Invalid argument" error at me. Tried executing the script with -i and had no luck either, just returns "http:: Invalid argument" instead.

Running the script on Windows 7 32bit through mingw (the one that comes with git by default). Have all the dependencies listed in the readme except for eyed3 and exif ones.

**Comment by Kattus** [comment]
Getting this as well, something defiantly broke.
```
katt@server2 ~ » ~/tools/furaffinity-dl/furaffinity-dl -r -p -c ~/tools/cookies-furaffinity-net.txt -o /mnt/jupiter/Temp/fa_dl/gallery/xiamtheferret gallery/xiamtheferret                                                        
INFO: eyed3 is not installed, no metadata will be injected into music files.
INFO: exiftool is not installed, no metadata will be injected into pictures.
2020-02-03 17:19:10 URL:https://www.furaffinity.net/gallery/xiamtheferret [92958] -> "/home/katt/.cache/furaffinity-dl/fa-dl.0JngnkbHzn" [1]
2020-02-03 17:19:11 URL:https://www.furaffinity.net/view/34664860/ [53323] -> "/home/katt/.cache/furaffinity-dl/fa-dl.0JngnkbHzn" [1]
--2020-02-03 17:19:11--  ftp://https/
           => ‘.listing’
Resolving https (https)... failed: Name or service not known.
wget: unable to resolve host address ‘https’
```

**Comment by Kattus** [comment]
I've sent a pull request to fix this, messed up linking to the issue it seems but whatever.

**Comment by Xerbo** [comment]
A very late thank you @Kattus, and closing this issue.
