### ISSUE TITLE
No address associated with hostname.

### ISSUE THREAD

**Issue by TogarUshindi** [Xerbo/furaffinity-dl#40]
Ubuntu 19.10

I used this tool once about a month ago. I came back to use it today and it's not working. Am I doing something wrong, or is the tool broken? Here's the output:

```
~/furaffinity-dl-master$ ./furaffinity-dl -c ./cookie.txt -o /path/to/download/to gallery/artist
INFO: eyed3 is not installed, no metadata will be injected into music files.
INFO: exiftool is not installed, no metadata will be injected into pictures.
2020-03-09 16:57:01 URL:https://www.furaffinity.net/gallery/artist [123456] -> "/home/user/.cache/furaffinity-dl/fa-dl.etcetcetc" [1]
2020-03-09 16:57:02 URL:https://www.furaffinity.net/view/12345678/ [123456] -> "/home/user/.cache/furaffinity-dl/fa-dl.etcetcetc" [1]
File already exists, skipping. Use -w to skip this check
2020-03-09 16:57:03 URL:https://www.furaffinity.net/view/12345678/ [12345] -> "/home/user/.cache/furaffinity-dl/fa-dl.etcetcetc" [1]
--2020-03-09 16:57:03--  ftp://https/
           => ‘.listing’
Resolving https (https)... failed: No address associated with hostname.
wget: unable to resolve host address ‘https’
```

Did something change on FA's server and so the script's address is mispointed?

**Comment by Xerbo** [comment]
It looks like you're running a version that didn't work properly (i should make a development branch), try running `git pull` to pull the latest commit.

**Comment by Xerbo** [comment]
If you didn't clone the repo with git then try `wget -N https://raw.githubusercontent.com/Xerbo/furaffinity-dl/master/furaffinity-dl` that should download the latest version of the script where this issue has been fixed.

**Comment by TogarUshindi** [comment]
Hello! Sorry, I haven't tried it yet. With everything going on it slipped my mind. I'll try this soon.

**Comment by TogarUshindi** [comment]
Just wanted to thank you for your help earlier. Finally got around to trying it with the new script and it works fine now.
