### ISSUE TITLE
It onlyworks on some galleries but not on others also it only downlodes SFW

### ISSUE THREAD

**Issue by Manni1000** [Xerbo/furaffinity-dl#41]
hey i use the tool on windows
i installed a Linux version from the Microsoft store 
 i tiped this in the command line:

cd /mnt/c/Users/Ich/Desktop/fu
chmod +x furaffinity-dl
./furaffinity-dl -o user -c /cookies/cookies.txt -p gallery/user 

but it works only on some users. :(
Aso it dosnt downlode Adult contet

**Comment by post-rex** [comment]
FA only lets you download adult content, if you are logged in with a account that has NSFW enabled, thats why we use the cookies.
There are also profiles that only let you view their gallery if you watch them (wierd thing tbh) so if you want to download from such a user you need to watch them.
I assume you might made a mistake when trying to set the cookies as you used a absolute path and i assume you got a folder called `cookies` with the file `cookies.txt` on the path `C:\Users\Ich\Desktop\fu`, but by using a absolute path FA-dl is trying to find that folder on your root file system in the WSL.
Basicly try removing the slash before the first cookies.

Also from your Windows user name `Ich` I assume you are german, if you prefere a german response tell me.

**Comment by Manni1000** [comment]
thanks i am going to try this. And you dont have to talk geman i understand you in english

**Comment by Xerbo** [comment]
Any progress on getting this to work?
