### ISSUE TITLE
Getting full size image URL is broken

### ISSUE THREAD

**Issue by Skiewuff** [Xerbo/furaffinity-dl#46]
Should be using //**d2**.facdn.net/art/ now:

image_url="$prefix$(grep --only-matching --max-count=1 ' href="//d2.facdn.net/art/.\+">Download' "$tempfile" | cut -d '"' -f 2)"

**Comment by Skiewuff** [comment]
Seems like FA keeps changing the host prefix. Probably depends on server status. So a smart script would check d.facdn and try to switch to d2.facdn if it's down

**Comment by Xerbo** [comment]
The python version is much more resilient to changes like this due to the fact that it uses a real HTML parser instead of regex and string splitting, I should really consider moving it into master and deprecating the bash version.
