### ISSUE TITLE
Skip files already downloaded? 

### ISSUE THREAD

**Issue by borderlineobsessive** [Xerbo/furaffinity-dl#47]
Hey! 

I'm not finding in the documentation any functionality for skipping files that have already been downloaded (on the python branch.) Could this be a feature that could be added?

**Comment by Xerbo** [comment]
Will do, shouldn't be hard to implement, I'm going to do it by downloading the page and getting the full meta information, this also allows us to renew the meta files but would still be pretty slow (this is how the bash version does it).
