### ISSUE TITLE
Gets stuck in inf download loop when trying to download folder from someone gallery with only 1 page

### ISSUE THREAD

**Issue by AuroraTheOtter** [Xerbo/furaffinity-dl#53]
> Xerbo Allow downloading of specific folders, ref #38 

https://pastebin.com/zCVhGjAf

**Comment by AuroraTheOtter** [comment]
moving this to #38

**Comment by Xerbo** [comment]
This seems to be some weirdness on FA's end, when you reach the end of a normal gallery you get `There are no submissions to list`, however, when browsing a folder you don't get that.
The easiest fix would be to check for the existence of the "next" button, or get the URL from it for the next page

**Comment by Xerbo** [comment]
Tried making some small changes, does the `fix-folder-dl` branch work fine?

**Comment by AuroraTheOtter** [comment]
> Tried making some small changes, does the `fix-folder-dl` branch work fine?

![WindowsTerminal_qNicHsvwl8](https://user-images.githubusercontent.com/79857876/109762494-66d43f80-7c3c-11eb-98d0-848a537689d9.png)

Yeah `fix-folder-dl ` branch  worked

**Comment by AuroraTheOtter** [comment]
When download a gallery after the update now does go thought all pages just stops at first.

![WindowsTerminal_2E8ZadyvmL](https://user-images.githubusercontent.com/79857876/110192564-91abd700-7e7a-11eb-93c7-463c484457e4.png)
