### ISSUE TITLE
Way to download folders

### ISSUE THREAD

**Issue by AuroraTheOtter** [Xerbo/furaffinity-dl#60]
![image](https://user-images.githubusercontent.com/79857876/122060565-1078be80-ce31-11eb-8c7b-1aac3c954763.png)
When download a folder you have to make sure to put everything after **/folder/** from the URL for a folder for example **406765/May-the-Best-Man-Win** instead of just **406765** then the downloader will get the correct url for the 2nd page.

Someone should probably add and example to the **README.md** and the **Help text that shows when you run the program** for this 

(Working)
![image](https://user-images.githubusercontent.com/79857876/122056445-ef15d380-ce2c-11eb-99a1-6bdf9a671947.png)

(Broken)
![WindowsTerminal_YZbNpHgOCv](https://user-images.githubusercontent.com/79857876/122059811-597c4300-ce30-11eb-8acf-5a4061cd93ae.png)

**Comment by dragonGod97677** [comment]
@AuroraTheOtter can you give me your cookies.txt file (of course remove your cookie string) because i having problem

there's an error saying my cookie file is invalid, been search for examples of cookie file online but i got nothing

**Comment by AuroraTheOtter** [comment]
> 
> 
> @AuroraTheOtter can you give me your cookies.txt file (of course remove your cookie string) because i having problem
> 
> there's an error saying my cookie file is invalid, been search for examples of cookie file online but i got nothing

![image](https://user-images.githubusercontent.com/79857876/125447836-13d30134-e7b1-4eaf-90c6-fe827a745a7e.png)
![image](https://user-images.githubusercontent.com/79857876/125447897-6c57f224-421a-41d7-beac-63c53e5c5311.png)
I uses this addon for getting my cookies file.

**Comment by dragonGod97677** [comment]
> > @AuroraTheOtter can you give me your cookies.txt file (of course remove your cookie string) because i having problem
> > there's an error saying my cookie file is invalid, been search for examples of cookie file online but i got nothing
> > @dragonGod97677
> 
> ![image](https://user-images.githubusercontent.com/79857876/125447836-13d30134-e7b1-4eaf-90c6-fe827a745a7e.png)
> ![image](https://user-images.githubusercontent.com/79857876/125447897-6c57f224-421a-41d7-beac-63c53e5c5311.png)
> I uses this addon for getting my cookies file. Remember you need to be using the new UI for FA not the old one.

Thanks for sending screen shot of your cookie file, sadly, for some reason, now it says im not logged in, it doesn't even give any error. Tho i tried my cookie file again but on the regular furaffinity-dl (bash version), it works, i can now download nsfw pictures

**Comment by dragonGod97677** [comment]
Here is my cookie file screenshot
![Screenshot_2021-07-13-23-56-17-62](https://user-images.githubusercontent.com/38875906/125485307-aac8b2d0-f571-4fee-8b99-385e10c79eda.png)

I don't know why im not logged in but im grateful that it works on regular bash version
![Screenshot_2021-07-13-23-57-40-83](https://user-images.githubusercontent.com/38875906/125485319-2c520006-00cf-46bf-860e-e5a6c1af2338.png)

**Comment by Xerbo** [comment]
Notices about folder downloading have been added in 29636db, sorry for the delay.

**Comment by dragonGod97677** [comment]
> Notices about folder downloading have been added in [29636db](https://github.com/Xerbo/furaffinity-dl/commit/29636db1e7c10386ae731fbba588fe7eec282d2e), sorry for the delay.

Hey xerbo, will this also apply to non python script?
