### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by f1refa11** [Xerbo/furaffinity-dl#72]
```
Not logged in, NSFW content is inaccessible
/data/data/com.termux/files/home/furaffinity-dl.py:209: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  next_button = s.find('button', class_='button standard', text="Next")
Unable to find next button
Finished downloading
```

it happens even if user has SFW content

**Comment by Xerbo** [comment]
Could you name a specific user this happens on as I am unable to reproduce

**Comment by f1refa11** [comment]
Are you able to download a specific gallery folder with cookies? Because i can't for some reason.

**Comment by f1refa11** [comment]
ok i know the problem: when the script was making a request to a site, it was getting cloudflare anti-ddos page. I fixed this by passing cookies which included the cloudflare's one, and setting browser agent to mine.
