### ISSUE TITLE
doesn't work through tor

### ISSUE THREAD

**Issue by faustdotmef** [Xerbo/furaffinity-dl#8]
torify ./grab gallery/kacey ./cookies.txt 
--2018-03-23 15:03:24--  http://www.furaffinity.net/gallery/kacey
Resolving www.furaffinity.net (www.furaffinity.net)... 104.20.69.59
Connecting to www.furaffinity.net (www.furaffinity.net)|104.20.69.59|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-03-23 15:03:24 ERROR 403: Forbidden.

same with https.

**Comment by Shnatsel** [comment]
Doesn't accessing it through Tor with web browser also produce 403? 

I don't think there's anything we can do in the code to fix it.

**Comment by faustdotmef** [comment]
i tried to change user agent but it didn't help. i don't know what they check when see tor exit node which browser has and this script doesn't.

**Comment by Helix-9** [comment]
They don't check for user agent, FurAffinity checks the exit's IP address and matches it with a database, if it matches (as it seems it did) it'll block you unless you score a exit node that isn't on the list, unfortunately this cannot be fixed nor improved by anyone (unless you can somehow specify witch exit node you want, but as i'm aware Tor doesn't let you do so)

**Comment by swats-the-floran** [comment]
well, after all i wrote my own grabber with python. works through tor well.

**Comment by swats-the-floran** [comment]
ah, and it doesn't need manual converting of cookies (which should be done on daily basis if you use tor).

**Comment by Shnatsel** [comment]
I wonder if it actually works reliably or you got lucky with an exit node that was not in the blacklist yet.

Anyway, if you've published the code, I'd be glad to link to it from furaffinity-dl readme. It's always nice to have alternatives.

**Comment by swats-the-floran** [comment]
yes, it's very stable. or course there are nodes blocked at furaffinity but fortunately not as many as about two years before.

code if published but not finished yet. it just downloads art from given gallery or submissions page. and you have to give it an initial setting by showing your mozilla directory with browser cookies. at first i want to make it work through clearnet and without cookies as well.

**Comment by Xerbo** [comment]
Due to the fact that this is furaffinity's backend blocking tor exit nodes and not the script I'm going to close this.
